global using EcoCode.Analyzers;
global using EcoCode.CodeFixes;
global using Microsoft.CodeAnalysis.CodeFixes;
global using Microsoft.CodeAnalysis.CSharp.Testing;
global using Microsoft.CodeAnalysis.Diagnostics;
global using Microsoft.CodeAnalysis.Testing;
global using Microsoft.CodeAnalysis.Testing.Verifiers;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using System.Threading.Tasks;
